
name: build_and_start_integration_tests

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build The Application
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test Homes.UnitTests/Homes.UnitTests.csproj --no-build --verbosity normal
